travis:
  secure:
    BINSTAR_TOKEN: PK/iwqfQLY8vFPKl8oR2DKGilyIereNsRLwBbWGf0/kzcgzY1K2VJ2sykY9fFPZ98Rt6U1W3KCjCH981xl8dqJZ7oBOmvHsOgdQgWtWyzofDFnCMubJCk9zLzZxeKxAuafbLk2aJ81et6QT95iKdzds0nTD4zx6jQGXe+8y4MB/rbklvMQ61/cIBj7tDCJlTJI0og4++ynls6oP2WgWaHHY2Sam9SWRW6+0KRu26FTWuYjzCLqeKaLBORZtykFfexFR4ey7dpswlFJnq3RsagEdOCCvyScAGKZFo+eXSr7hJll0QmqiSRCZsJY1gQeUWNLwmSu+NPrGqQz5tmQotVp+Z+PvU1FckrDSkteipSlnNtwHqYJzoBWtPqgUzgP8zwIOiopzChATmXKzYHHZllhi8qJBiDNNzMbVZzLXahpjiw8il8OnkQkX+npUQ9zZunvEHaLd+O3Ehy5Y6JgA+2UgVILRA/4qyGvjPYvx/WalxMfylKcevqvZHorjNpSkslhPyHZlitYt2tCjsdclHovHSRHUrYuGWEdEOeBmXyDIeNznOXk/3nRrrIxteX1XlPyDXH+426zfC0ZIgWS+hFhG9SKf5lwf6zlurjekvR68pyZta9btgDgT4TcKBdkCIevcQSUsxwmfkZ0H4tAJx3Cr97BSxbcGBf1KQFmC9uS4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
